Add GHA workflow to build ee image on PR merge
opdev/opcap-ansible pull request #10
Opened 2023-07-14 19:31 UTC by madorn

Adds a GitHub Action workflow to build the execution environment image and push to `quay.io/opdev` when a PR merges that impacts `execution-environment.yml`, `requirements.yml`, or `requirements.txt`.

Issue #8

2023-07-14 19:49 UTC, mrhillsman commented
@madorn looks like changes other than requirements.txt and .github/workflows/opcap-ansible-ee-build.yml aren't needed. i'm guessing you just need to rebase since the other changes merged with #6

2023-07-14 19:50 UTC, mrhillsman requested changes
@madorn looks like changes other than requirements.txt and .github/workflows/opcap-ansible-ee-build.yml aren't needed. i'm guessing you just need to rebase since the other changes merged with #6

2023-07-15 00:40 UTC, mrhillsman commented
/lgtm

2023-07-15 00:40 UTC, mrhillsman approved these changes

2023-07-17 02:37 UTC, bcrochet requested changes
Just one small change.

2023-07-18 13:44 UTC, merged